language: node_js
node_js:
- '5.0'
addons:
  apt:
    packages:
    - ncftp
script:
- make build
after_success:
- ncftp -u $FTP_USER -p $FTP_PASS $FTP_HOST <<< "rm -rf ./H941000/page"
- ncftpput -R -v -u $FTP_USER -p $FTP_PASS $FTP_HOST ./ .tmp/*
branches:
  only:
    - master
env:
  global:
  - secure: ekUNyq2mirmVmQ3BMTomHH3Iv3OgktNmwcF+rwYpVgKCFbIefHRkp6+EvlECsFr7qHYddlwiwmSMLyygYuQPQA57zcIGBuFeUf2+eN9vHkmmLEM5Yjp1lD64OvhmXnGieVzX+LJHHfYgLon67HrNjS8uA8Cbec8B2/5KQG9r4I67G+huH4yi+T8dM3zV445hp4RORs+oil/MwfAoMQkB7oAS0oTQl4h767mavscC1cQdPAGTCKQ25GhW8dHOJsJtDxcm615ImdfvGOq7ftjxEmttUCv5o8dEDP916HR0hGbjcWu2LeaqtZDJp5Djuba+L8zWdLj8FlxPPBbrab/If14XJmLpBjpiYkTAOoINGT3JmoaLFFFfyzTfwAYt2/Wcs8wv5DpDyo9VUS+CGgWvBjgvwcBe28Gt8esaK7uiFYBOpl9v9vpx1vG28tOQHvrE8iBBtEAEk99ZmgCc0v2Y9FXwXpptfbTlnDzAJnKEOo9bYD0oUh/QNmS3kBpCEanzUw7O3FsKAt8ezME5dv8xph7yqvRJNY0/m/vhTJ0BGkgWknkz1gbRiV3S0tj22A5VeE3EDHsM6XdYZy9xcl0jsdgEMMbRVwLzP2HcCeRloitARdnWp+2NcvoBanFkWWFz6t5tSefiUXNmT8ybFQRieps5tJ73Vd8jMNgvC5zbXEE=
  - secure: PEvF9DJ8mXAsV4151Ss8zcOHCz6oR3i9ljcqtbStF+H8twrPvV8Bhfg36Y1FDxEm9O/+GA+EArQJAjrpcyhSgnvjvhN2xi8GbExGI+f5K8kpT/UcPQNFa/FBjl9CFuvPG5dqZRsaDRpV7ypvAYUvUgUNMk2u1wwzoKCmbCD0duZf+GY6lldcC/QzG8IziN7THQxvf9GSA+bNJiqPOEfTFf523HhPLYmZKIBLLaqEXKR0kgtfvlD83eyoIGUiAHU+3cZOnsZm2o1m0AV5MU4jIG1E60nwGZGre7/DcxN1alpZrII/J5cTclSJpOXv7rfOG4r2x9MOq/Gj0KUOVCE4psIG/22qFlOwH6+bHAbB/pHV6d3EwqafgBnSleGfei+Gks523uxuw4fNO6jy7SWO6rZGjXC4NvPLT53eUDiMgOTzMGnYYWwRH3o53sxmSrFwuCW6IuWsMaJDQ7RDnoh/tiWprAKFoogety1sHTQGbc0JBKPm1v7+gKASA0lTjG7AcFXmFCQ8/hhxcFIhRUR1bWQPRDw6b3GRt55jzELJeV8o/acDlZc6OY67Ho116EgG1xCkYwYVC13VOed+liSBYPjqF/QLfFRIFg6VDcxL0ZtWNu3pf/G7o/NYc9nkD3xgi1fGeKBcnZOilyEvTlJW8tmWR9Pm+jvUyaXnxh9oGWM=
  - secure: k6SSVt/+babLuD1P7j+Wjfl2SQya4Dc1EnX2ILNqE9EXzGFtaSjn1lIGMoIx+809MQFjAT+WTobE6x8fgafe9YSOVLCFI2vKBZmnnTMe12TfhplX5mpTG7V7hgbGyGHr4g3epa5rqGzliWLVYkb8INRjjkjGiVTsyddmOlBlTN67zg1iUM+o+kf/E/V6cL4/XtgQxowIEvzSu5gXmc/YxktbgOQpmOczrRxpst9VPf3eS7WSe1d+JwvZSCoSFgj0xTZb+6EFSW1fB9NZKY1ZgxU/SBDasCqiM6la45j8v6U2dGsq/KIFpROGFKSLzqpdz3/ExFQq0eiLDLBpu3atiuw9jbCGjmRGFYUqOuw5M/TTfj/+7BvC6XTPx93Rcum/OsNcSChmfJiio9xnXrN4wT02f138Zx4rAFAO5UrhBCmwAQFUgm1lJSw7f0Tcg/QE4jpmal1ZncXEH9nXYIcdo+ct9uq+G8Yzv4zW3xevka5mFoWjbqWdYnPFO6v3dCXx8FVTnY1g6BiPJ++P/nW2V4ySmPI+18ViYXUUSHROICOr+2+b4YmlFKC7luYhaGbpnHt8iNP0eMg2OOxQvarbRllX9t+aUHEfJbXRf5DwcZY9jfwMcszkCNV2NG0S8MnSNlGU1fl3XOx1kG4YmVqmH/5LUeY0V6hyL8zlA5ZdEdE=
